### ISSUE TITLE
Recording audio in Safari in audio/wav format

### ISSUE THREAD

**Issue by petrovy4** [chrisguttandin/extendable-media-recorder-wav-encoder#400]
I've got an issue using extendable-media-recorder together with extendable-media-recorder-wav-encoder in Safari. Resulting audio is missing some random chunks of audio data. Using it exactly as described [here](https://github.com/chrisguttandin/extendable-media-recorder#usage).
UPDATE: attaching source file
[AudioMessageInput.tsx.txt](https://github.com/chrisguttandin/extendable-media-recorder-wav-encoder/files/9023011/AudioMessageInput.tsx.txt)
.

**Comment by chrisguttandin** [comment]
Hi @petrovy4, thanks for reporting this. Can you share which version of Safari it was? Was it on iOS or on macOS? Can you reproduce it repeatedly?

**Comment by petrovy4** [comment]
Hi, @chrisguttandin . Here is some info: Safari 15.5 (17613.2.7.1.8), macOS Monterey 12.4 (21F79). It's also reproducible in Safari on iOS 15.5. And yep, it's constantly reproducible.

**Comment by chrisguttandin** [comment]
I can confirm that there is something not going well in Safari. But I don't really know how to fix it yet.

To me it looks like Safari has the tendency to insert some all-zero-blocks at the beginning. Towards the end of a recording the exact opposite seems to happen. There are blocks of missing samples. All those blocks seem to have a length which is a multiple of 128 (aka the render quantum).

In Safari an `AudioWorklet` is used to get the PCM sample data. I inserted some instrumentation code in the `AudioWorklet` and apparently the zero samples and missing samples are already passed to the `process()` function. 

I think just skipping the zeros to not include them in the recording would not help as there might be recordings which are actually silent at the beginning. Recovering the missing samples is probably impossible.

Currently I have no idea how this could be fixed. :-( I'm happy for any suggestions.

**Comment by petrovy4** [comment]
Tnx for your investigation, Christoph! No idea as well, and looks like it used to work quite well recently, maybe Safari received some updates which broke functionality. Maybe MediaRecorder in Safari uses several channels by default (just guessing...) and it switches data from one channel to another, maybe we need to merge this data from "all" channels.

**Comment by chrisguttandin** [comment]
Unfortunately there is no way (that I know of) to use the `MediaRecorder` in Safari to get PCM data. That's why `extendable-media-recorder` will internally use the Web Audio API and an `AudioWorklet` to get the PCM data. The `MediaStream` gets fed into the `AudioContext` with a `MediaStreamAudioSourceNode`. From my tests it looks like the missing samples never reach the `AudioWorklet` and I'm not sure what can be done in userland to fix this. :-(

**Comment by jsom** [comment]
Hi! We've discovered the same issue with our own recording `AudioWorklet`. No workaround yet, but I did want to confirm it's working for Safari 14 and broken for Safari 15.

**Comment by chrisguttandin** [comment]
I was able to reproduce the issue (or a different issue) locally.  The integration tests record a sinewave and sometimes the analysis showed that there were discontinuities in the recording. It looks like Safari throttles the audio processing when the page is not visible. As a result the `AudioWorkletProcessor` gets not called at all for some time. I added an expectation test to keep track of that bug (which is probably a feature to some people).

Luckily it can be mitigated by adding a silent `ConstantSourceNode`.

There is still an issue that Safari sometimes inserts blocks (multiples of the render quantum) of silence. This  usually happens at the very beginning. I guess this happens when Safari realizes that it needs to increase the internal buffer. I have no fix for this yet. But I think it's a separate issue.

Please feel free to re-open this or to create a new issue in case the problem that affected you was a different one and isn't fixed by the changes I made.
